tetcore factoring

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,6 +1,6 @@
 # .gitlab-ci.yml
 #
-# substrate
+# tetcore
 #
 # pipelines can be triggered manually in the web
 
@@ -9,7 +9,7 @@
 #
 # my-example-job:
 #   stage:                           test # One of the stages listed below this job (required)
-#   image:                           paritytech/tools:latest # Any docker image (required)
+#   image:                           tetcoin/tools:latest # Any docker image (required)
 #   allow_failure:                   true # Allow the pipeline to continue if this job fails (default: false)
 #   needs:
 #     - job:                         test-linux # Any jobs that are required to run before this job (optional)
@@ -41,7 +41,7 @@ variables:                         &default-vars
   ARCH:                            "x86_64"
   # FIXME set to release
   CARGO_UNLEASH_INSTALL_PARAMS:    "--version 1.0.0-alpha.11"
-  CARGO_UNLEASH_PKG_DEF:           "--skip node node-* pallet-template pallet-example pallet-example-* subkey chain-spec-builder"
+  CARGO_UNLEASH_PKG_DEF:           "--skip node node-* pallet-template pallet-example pallet-example-* tetkey chain-spec-builder"
 
 default:
   cache:                           {}
@@ -56,11 +56,11 @@ default:
 
 .kubernetes-build:                 &kubernetes-build
   tags:
-    - kubernetes-parity-build
+    - kubernetes-tetsy-build
   interruptible:                   true
 
 .docker-env:                       &docker-env
-  image:                           paritytech/ci-linux:production
+  image:                           tetcoin/ci-linux:production
   before_script:
     - rustup show
     - cargo --version
@@ -94,7 +94,7 @@ default:
 #### stage:                       .pre
 
 skip-if-draft:
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   stage:                           .pre
   rules:
@@ -109,21 +109,21 @@ skip-if-draft:
 
 check-runtime:
   stage:                           check
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   rules:
     - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
   variables:
     <<:                            *default-vars
-    GITLAB_API:                    "https://gitlab.parity.io/api/v4"
-    GITHUB_API_PROJECT:            "parity%2Finfrastructure%2Fgithub-api"
+    GITLAB_API:                    "https://gitlab.tetcoin.org/api/v4"
+    GITHUB_API_PROJECT:            "tetsy%2Finfrastructure%2Fgithub-api"
   script:
     - ./.maintain/gitlab/check_runtime.sh
   allow_failure:                   true
 
 check-signed-tag:
   stage:                           check
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   rules:
     - if: $CI_COMMIT_REF_NAME =~ /^ci-release-.*$/
@@ -133,7 +133,7 @@ check-signed-tag:
 
 check-line-width:
   stage:                           check
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   rules:
     - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
@@ -143,14 +143,14 @@ check-line-width:
 
 test-dependency-rules:
   stage:                           check
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   script:
     - .maintain/ensure-deps.sh
 
 test-prometheus-alerting-rules:
   stage:                           check
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   rules:
     - if: $CI_COMMIT_BRANCH
@@ -206,16 +206,16 @@ cargo-check-benches:
   <<:                              *test-refs
   script:
     - SKIP_WASM_BUILD=1 time cargo +nightly check --benches --all
-    - cargo run --release -p node-bench -- ::node::import::native::sr25519::transfer_keep_alive::paritydb::small
+    - cargo run --release -p node-bench -- ::node::import::native::sr25519::transfer_keep_alive::tetsydb::small
     - cargo run --release -p node-bench -- ::trie::read::small
     - sccache -s
 
-cargo-check-subkey:
+cargo-check-tetkey:
   stage:                           test
   <<:                              *docker-env
   <<:                              *test-refs
   script:
-    - cd ./bin/utils/subkey
+    - cd ./bin/utils/tetkey
     - SKIP_WASM_BUILD=1 time cargo check --release
     - sccache -s
 
@@ -253,7 +253,7 @@ test-linux-stable:                 &test-linux
   script:
     # this job runs all tests in former runtime-benchmarks, frame-staking and wasmtime tests
     - time cargo test --workspace --locked --release --verbose --features runtime-benchmarks --manifest-path bin/node/cli/Cargo.toml
-    - SUBSTRATE_TEST_TIMEOUT=1 time cargo test -p substrate-test-utils --release --verbose --locked -- --ignored timeout
+    - TETCORE_TEST_TIMEOUT=1 time cargo test -p tetcore-test-utils --release --verbose --locked -- --ignored timeout
     - sccache -s
 
 unleash-check:
@@ -313,7 +313,7 @@ check-web-wasm:
   <<:                              *test-refs
   script:
     # WASM support is in progress. As more and more crates support WASM, we
-    # should add entries here. See https://github.com/paritytech/substrate/issues/2416
+    # should add entries here. See https://github.com/tetcoin/tetcore/issues/2416
     # Note: we don't need to test crates imported in `bin/node/cli`
     - time cargo build --manifest-path=client/consensus/aura/Cargo.toml --target=wasm32-unknown-unknown --features getrandom
     # Note: the command below is a bit weird because several Cargo issues prevent us from compiling the node in a more straight-forward way.
@@ -355,7 +355,7 @@ cargo-check-macos:
 
 check-polkadot-companion-status:
   stage:                           build
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   rules:
     - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
@@ -390,7 +390,7 @@ test-browser-node:
   script:
     - cargo +nightly test --target wasm32-unknown-unknown -p node-browser-testing -Z features=itarget
 
-build-linux-substrate:             &build-binary
+build-linux-tetcore:             &build-binary
   stage:                           build
   <<:                              *collect-artifacts
   <<:                              *docker-env
@@ -407,25 +407,25 @@ build-linux-substrate:             &build-binary
     - job:                         test-linux-stable
       artifacts:                   false
   before_script:
-    - mkdir -p ./artifacts/substrate/
+    - mkdir -p ./artifacts/tetcore/
   script:
     - WASM_BUILD_NO_COLOR=1 time cargo build --release --verbose
-    - mv ./target/release/substrate ./artifacts/substrate/.
-    - echo -n "Substrate version = "
+    - mv ./target/release/tetcore ./artifacts/tetcore/.
+    - echo -n "Tetcore version = "
     - if [ "${CI_COMMIT_TAG}" ]; then
-        echo "${CI_COMMIT_TAG}" | tee ./artifacts/substrate/VERSION;
+        echo "${CI_COMMIT_TAG}" | tee ./artifacts/tetcore/VERSION;
       else
-        ./artifacts/substrate/substrate --version |
-          sed -n -E 's/^substrate ([0-9.]+.*-[0-9a-f]{7,13})-.*$/\1/p' |
-            tee ./artifacts/substrate/VERSION;
+        ./artifacts/tetcore/tetcore --version |
+          sed -n -E 's/^tetcore ([0-9.]+.*-[0-9a-f]{7,13})-.*$/\1/p' |
+            tee ./artifacts/tetcore/VERSION;
       fi
-    - sha256sum ./artifacts/substrate/substrate | tee ./artifacts/substrate/substrate.sha256
+    - sha256sum ./artifacts/tetcore/tetcore | tee ./artifacts/tetcore/tetcore.sha256
     - printf '\n# building node-template\n\n'
-    - ./.maintain/node-template-release.sh ./artifacts/substrate/substrate-node-template.tar.gz
-    - cp -r .maintain/docker/substrate.Dockerfile ./artifacts/substrate/
+    - ./.maintain/node-template-release.sh ./artifacts/tetcore/tetcore-node-template.tar.gz
+    - cp -r .maintain/docker/tetcore.Dockerfile ./artifacts/tetcore/
     - sccache -s
 
-build-linux-subkey:                &build-subkey
+build-linux-tetkey:                &build-tetkey
   stage:                           build
   <<:                              *collect-artifacts
   <<:                              *docker-env
@@ -439,25 +439,25 @@ build-linux-subkey:                &build-subkey
       when: manual
       allow_failure: true
   needs:
-    - job:                         cargo-check-subkey
+    - job:                         cargo-check-tetkey
       artifacts:                   false
   before_script:
-    - mkdir -p ./artifacts/subkey
+    - mkdir -p ./artifacts/tetkey
   script:
-    - cd ./bin/utils/subkey
+    - cd ./bin/utils/tetkey
     - SKIP_WASM_BUILD=1 time cargo build --release --verbose
     - cd -
-    - mv ./target/release/subkey ./artifacts/subkey/.
+    - mv ./target/release/tetkey ./artifacts/tetkey/.
     - echo -n "Subkey version = "
-    - ./artifacts/subkey/subkey --version |
-        sed -n -E 's/^subkey ([0-9.]+.*)/\1/p' |
-          tee ./artifacts/subkey/VERSION;
-    - sha256sum ./artifacts/subkey/subkey | tee ./artifacts/subkey/subkey.sha256
-    - cp -r .maintain/docker/subkey.Dockerfile ./artifacts/subkey/
+    - ./artifacts/tetkey/tetkey --version |
+        sed -n -E 's/^tetkey ([0-9.]+.*)/\1/p' |
+          tee ./artifacts/tetkey/VERSION;
+    - sha256sum ./artifacts/tetkey/tetkey | tee ./artifacts/tetkey/tetkey.sha256
+    - cp -r .maintain/docker/tetkey.Dockerfile ./artifacts/tetkey/
     - sccache -s
 
-build-macos-subkey:
-  <<:                              *build-subkey
+build-macos-tetkey:
+  <<:                              *build-tetkey
   tags:
     - osx
 
@@ -495,14 +495,14 @@ build-rust-doc:
     <<:                            *default-vars
     GIT_STRATEGY:                  none
     DOCKERFILE:                    $PRODUCT.Dockerfile
-    IMAGE_NAME:                    docker.io/parity/$PRODUCT
+    IMAGE_NAME:                    docker.io/tetsy/$PRODUCT
   before_script:
     - cd ./artifacts/$PRODUCT/
     - VERSION="$(cat ./VERSION)"
     - echo "${PRODUCT} version = ${VERSION}"
     - test -z "${VERSION}" && exit 1
   script:
-    - test "$Docker_Hub_User_Parity" -a "$Docker_Hub_Pass_Parity" ||
+    - test "$Docker_Hub_User_Tetsy" -a "$Docker_Hub_Pass_Tetsy" ||
         ( echo "no docker credentials provided"; exit 1 )
     - buildah bud
         --format=docker
@@ -511,75 +511,75 @@ build-rust-doc:
         --tag "$IMAGE_NAME:$VERSION"
         --tag "$IMAGE_NAME:latest"
         --file "$DOCKERFILE" .
-    - echo "$Docker_Hub_Pass_Parity" |
-        buildah login --username "$Docker_Hub_User_Parity" --password-stdin docker.io
+    - echo "$Docker_Hub_Pass_Tetsy" |
+        buildah login --username "$Docker_Hub_User_Tetsy" --password-stdin docker.io
     - buildah info
     - buildah push --format=v2s2 "$IMAGE_NAME:$VERSION"
     - buildah push --format=v2s2 "$IMAGE_NAME:latest"
     - buildah logout "$IMAGE_NAME"
 
-publish-docker-substrate:
+publish-docker-tetcore:
   stage:                           publish
   <<:                              *build-push-docker-image
   # collect VERSION artifact here to pass it on to kubernetes
   <<:                              *collect-artifacts
   needs:
-    - job:                         build-linux-substrate
+    - job:                         build-linux-tetcore
       artifacts:                   true
   variables:
     <<:                            *docker-build-vars
-    PRODUCT:                       substrate
+    PRODUCT:                       tetcore
   after_script:
     # only VERSION information is needed for the deployment
     - find ./artifacts/ -depth -not -name VERSION -type f -delete
 
-publish-docker-subkey:
+publish-docker-tetkey:
   stage:                           publish
   <<:                              *build-push-docker-image
   needs:
-    - job:                         build-linux-subkey
+    - job:                         build-linux-tetkey
       artifacts:                   true
   variables:
     <<:                            *docker-build-vars
-    PRODUCT:                       subkey
+    PRODUCT:                       tetkey
 
 publish-s3-release:
   stage:                           publish
   <<:                              *build-refs
   <<:                              *kubernetes-build
   needs:
-    - job:                         build-linux-substrate
+    - job:                         build-linux-tetcore
       artifacts:                   true
-    - job:                         build-linux-subkey
+    - job:                         build-linux-tetkey
       artifacts:                   true
-  image:                           paritytech/awscli:latest
+  image:                           tetcoin/awscli:latest
   variables:
     GIT_STRATEGY:                  none
-    BUCKET:                        "releases.parity.io"
-    PREFIX:                        "substrate/${ARCH}-${DOCKER_OS}"
+    BUCKET:                        "releases.tetcoin.org"
+    PREFIX:                        "tetcore/${ARCH}-${DOCKER_OS}"
   script:
-    - aws s3 sync ./artifacts/ s3://${BUCKET}/${PREFIX}/$(cat ./artifacts/substrate/VERSION)/
+    - aws s3 sync ./artifacts/ s3://${BUCKET}/${PREFIX}/$(cat ./artifacts/tetcore/VERSION)/
     - echo "update objects in latest path"
-    - aws s3 sync s3://${BUCKET}/${PREFIX}/$(cat ./artifacts/substrate/VERSION)/ s3://${BUCKET}/${PREFIX}/latest/
+    - aws s3 sync s3://${BUCKET}/${PREFIX}/$(cat ./artifacts/tetcore/VERSION)/ s3://${BUCKET}/${PREFIX}/latest/
   after_script:
     - aws s3 ls s3://${BUCKET}/${PREFIX}/latest/
         --recursive --human-readable --summarize
 
 publish-s3-doc:
   stage:                           publish
-  image:                           paritytech/awscli:latest
+  image:                           tetcoin/awscli:latest
   allow_failure:                   true
   needs:
     - job:                         build-rust-doc
       artifacts:                   true
-    - job:                         build-linux-substrate
+    - job:                         build-linux-tetcore
       artifacts:                   false
   <<:                              *build-refs
   <<:                              *kubernetes-build
   variables:
     GIT_STRATEGY:                  none
-    BUCKET:                        "releases.parity.io"
-    PREFIX:                        "substrate-rustdoc"
+    BUCKET:                        "releases.tetcoin.org"
+    PREFIX:                        "tetcore-rustdoc"
   script:
     - test -r ./crate-docs/index.html || (
         echo "./crate-docs/index.html not present, build:rust:doc:release job not complete";
@@ -593,7 +593,7 @@ publish-s3-doc:
 
 publish-draft-release:
   stage:                           publish
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   rules:
     - if: $CI_COMMIT_REF_NAME =~ /^ci-release-.*$/
     - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
@@ -609,7 +609,7 @@ publish-to-crates-io:
     - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
   script:
     - cargo install cargo-unleash ${CARGO_UNLEASH_INSTALL_PARAMS}
-    - cargo unleash em-dragons --no-check --owner github:paritytech:core-devs ${CARGO_UNLEASH_PKG_DEF}
+    - cargo unleash em-dragons --no-check --owner github:tetcoin:core-devs ${CARGO_UNLEASH_PKG_DEF}
   allow_failure:                   true
 
 #### stage:                        deploy
@@ -622,10 +622,10 @@ deploy-prometheus-alerting-rules:
   interruptible:                   true
   retry:                           1
   tags:
-    - kubernetes-parity-build
-  image:                           paritytech/kubetools:latest
+    - kubernetes-tetsy-build
+  image:                           tetcoin/kubetools:latest
   environment:
-    name: parity-mgmt-polkadot-alerting
+    name: tetsy-mgmt-polkadot-alerting
   variables:
     NAMESPACE:                     monitoring
     PROMETHEUSRULE:                prometheus-k8s-rules-polkadot-alerting
@@ -646,10 +646,10 @@ trigger-simnet:
     # this job runs only on nightly pipeline with the mentioned variable, against `master` branch
     - if: $CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "schedule" && $PIPELINE == "nightly"
   needs:
-    - job:                         publish-docker-substrate
+    - job:                         publish-docker-tetcore
       artifacts:                   false
   trigger:
-    project:                       parity/simnet
+    project:                       tetsy/simnet
     branch:                        master
     strategy:                      depend
 
@@ -659,10 +659,10 @@ trigger-simnet:
     # this job runs only on nightly pipeline with the mentioned variable, against `master` branch
     - if: $CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "schedule" && $PIPELINE == "nightly"
   needs:
-    # script will fail if there is no artifacts/substrate/VERSION
-    - job:                         publish-docker-substrate
+    # script will fail if there is no artifacts/tetcore/VERSION
+    - job:                         publish-docker-tetcore
       artifacts:                   true
-  image:                           parity/azure-ansible:v2
+  image:                           tetsy/azure-ansible:v2
   allow_failure:                   true
   interruptible:                   true
   tags:
@@ -692,7 +692,7 @@ validator 4 4:
 
 check-labels:
   stage:                           .post
-  image:                           paritytech/tools:latest
+  image:                           tetcoin/tools:latest
   <<:                              *kubernetes-build
   rules:
     - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
